#!/bin/bash

# Doc: voir le fichier gitclone.md

# usage:
# $ gitclone nomdepot inputfile outputfolder
# -nomdepot: nom du dépot (Github ou Gitlab)
# -inputfile: nom du fichier CSV d'entrée contenant les id github ainsi que les identifiants
# -outputfolder: nom du dossier de sortie (peut être `.` pour le dossier courant).


# FQDN du repo (valeur par défaut)
repourl=github.com

# parametrage colonnes fichier CSV d'entrée (commence à index 0)
col_groupe=0
col_idgithub=2
col_id=1

# Default field separator in input file
sep=";"

# for a future switch
#mode=https
mode=git

# args:
# 1: nom dépot
# 2: nom fichier csv contenant les id github
# 3: chemin destination


function usage()
{
	echo "gitclone nomdepot inputfile [outputfolder]"
	exit 1
}

if [ "$1" == "" ]
then
	echo "Erreur, manque nom des dépots"
	usage
fi
repo=$1

if [ "$2" == "" ]
then
	echo "Erreur, manque nom fichier CSV d'entrée"
	usage
fi
input_file=$2

if ! [ -f $input_file ]; then
	echo " -Erreur: fichier '$input_file' introuvable!"
	exit 2
fi

if [ -f gitclone.conf ]; then
	echo "Lecture index de colonne dans gitclone.conf"
	source gitclone.conf
fi

dst=.
if ! [ "$3" == "" ]
then
	dst=$3
fi
mkdir -p $dst

echo -e "Indexs dans fichier csv:\n -groupe=$col_groupe\n -id Github=$col_idgithub\n -Identifiant=$col_id"

# verification

while IFS=$sep read -ra tab
do
	word=${tab[0]}
	if ! [ "${word:0:1}" == "#" ]
	then
		gr=${tab[$col_groupe]}
		idurn=${tab[$col_id]}
		idgh=${tab[$col_idgithub]}
		echo "Vérification 1er depot: groupe='$gr' id='$idurn' id-depot='$idgh'"
		break;
	fi
done < $input_file

read -p "Correct? (O/N)" rep
rep=${rep:-O}
if [ "$rep" != "O" ] && [ "$rep" != "o" ]  ; then echo "Abandon!"; exit 1; fi

today=$(date +"%Y%m%d-%H%M")
logfile=log_clonage_${repo}_$today.csv
echo "# log clonage Github du $today, nom depot=$repo">$logfile


dest=$dst/github_${repo}_${today}
mkdir -p $dest

echo "Clonage Github du $today, dest=$dest, depot=$repo"

# compteurs
c_err=0
c_ok=0
c_li=0

while IFS=$sep read -ra tab
do
	word=${tab[0]}
	if ! [ "${word:0:1}" == "#" ]
	then
		((c_li+=1))
		gr=${tab[$col_groupe]}
		idurn=${tab[$col_id]}
		idgh=${tab[$col_idgithub]}
		echo -n "$gr;$idurn;$idgh;" >> $logfile
		echo -n " -$c_li: clonage depot de '$idurn', gr=$gr, Id='$idgh' => " >> $logfile
		echo -n " -$c_li: clonage depot de '$idurn', gr=$gr, Id='$idgh' => "
		mkdir -p $dest/$gr
		if [ $mode == https ]
		then
			git clone https://$repourl/$idgh/$repo.git "$dest/$gr/$idurn" 1>/dev/null 2>/dev/null
		else
			git clone git@$repourl:$idgh/$repo.git "$dest/$gr/$idurn" 1>/dev/null 2>/dev/null
		fi
		if [ $? != 0 ]
		then
			((c_err+=1))
			echo "ECHEC" >> $logfile
			echo -e "\e[1;91mECHEC\e[0m"
		else
			((c_ok+=1))
			echo "succès" >> $logfile
			echo -e "\e[1;92msuccès\e[0m"
		fi
	fi
done < $input_file

echo -e "*** bilan ***: total de $c_li lignes\n -succès:$c_ok\n -echecs:$c_err"

